### ISSUE TITLE
AttributeError first time calling DictFeat

### ISSUE THREAD

**Issue by JKarsch** [nspyre-org/nspyre#22]
With XPSQ8 driver, the first time trying to read the abs_position from the XPS (a dict_feat) this error appears.
```
Traceback (most recent call last):
  File "C:\Users\Samwise\miniconda3\envs\nspyre\lib\site-packages\nspyre\spyrelet\spyrelet.py", line 183, in run
    self.initialize(*args, **kwargs)
  File "C:\Users\Samwise\LL225work\nspyre\spyrelets\setup_navigation_calibration.py", line 1118, in initialize
    self.initial_z_pos = self.xps.abs_position['Group3.Pos']
  File "C:\Users\Samwise\miniconda3\envs\nspyre\lib\site-packages\rpyc\core\netref.py", line 274, in method
    return syncreq(_self, consts.HANDLE_CALLATTR, name, args, kwargs)
  File "C:\Users\Samwise\miniconda3\envs\nspyre\lib\site-packages\rpyc\core\netref.py", line 76, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "C:\Users\Samwise\miniconda3\envs\nspyre\lib\site-packages\rpyc\core\protocol.py", line 469, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "C:\Users\Samwise\miniconda3\envs\nspyre\lib\site-packages\rpyc\core\async_.py", line 102, in value
    raise self._obj
_get_exception_class.<locals>.Derived: 'NoneType' object has no attribute 'index'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "C:\Users\Samwise\miniconda3\envs\nspyre\lib\site-packages\rpyc\core\protocol.py", line 320, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "C:\Users\Samwise\miniconda3\envs\nspyre\lib\site-packages\rpyc\core\protocol.py", line 619, in _handle_callattr
    return self._handle_call(obj, args, kwargs)
  File "C:\Users\Samwise\miniconda3\envs\nspyre\lib\site-packages\rpyc\core\protocol.py", line 593, in _handle_call
    return obj(*args, **dict(kwargs))
  File "C:\Users\Samwise\miniconda3\envs\nspyre\lib\site-packages\pimpmyclass\dictprops.py", line 137, in __getitem__
    return DictProperty.getitem(self.df, self.instance, key)
  File "C:\Users\Samwise\miniconda3\envs\nspyre\lib\site-packages\pimpmyclass\dictprops.py", line 76, in getitem
    return self.subproperty(instance, key).__get__(instance)
  File "C:\Users\Samwise\miniconda3\envs\nspyre\lib\site-packages\pimpmyclass\props.py", line 83, in __get__
    self.get_notify(instance, value)
  File "C:\Users\Samwise\miniconda3\envs\nspyre\lib\site-packages\pimpmyclass\props.py", line 462, in get_notify
    self.store(instance, value)
  File "C:\Users\Samwise\miniconda3\envs\nspyre\lib\site-packages\pimpmyclass\props.py", line 538, in store
    getattr(instance, self.name.name + '_changed').emit(value, old_value, self.name.key)
  File "C:\Users\Samwise\miniconda3\envs\nspyre\lib\site-packages\PySignal.py", line 45, in emit
    slot()(*args, **kwargs)
  File "C:\Users\Samwise\miniconda3\envs\nspyre\lib\site-packages\nspyre\inserv\inserv.py", line 290, in update_mongo_dictfeat
    {'$set': {'value.{}'.format(keys.index(key)): value}},
AttributeError: 'NoneType' object has no attribute 'index'
```

**Comment by jacobfeder** [comment]
Hey sorry I missed this before - did you ever figure it out? I may know why but would have to take a closer look at the driver.

**Comment by mtsolmn** [comment]
@JKarsch hey, just checking that you were able to figure this out?

**Comment by JKarsch** [comment]
I didn't figure out how to prevent the underlying issue but I got around it by calling the XPS dict_feat in a try loop, assuming it will fail the first time, and then moving on with the rest of the code because it only throws an error the first time.
`while got_z == False:
try:
    tries = tries + 1
    self.initial_z_pos = self.xps.abs_position['Group3.Pos'] # this line throws the error
    got_z = True`
