### ISSUE TITLE
Spyrelet sending non Q_ value

### ISSUE THREAD

**Issue by gwolfowiczANL** [nspyre-org/nspyre#30]
When passing an array defined by np.linspace() for a sweep in a typical spyrelet "main" loop, I got the error:

`Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\rpyc\core\protocol.py", line 320, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\rpyc\core\protocol.py", line 615, in _handle_setattr
    return self._access_attr(obj, name, (value,), "_rpyc_setattr", "allow_setattr", setattr)
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\rpyc\core\protocol.py", line 537, in _access_attr
    return accessor(obj, name, *args)
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\pimpmyclass\props.py", line 93, in __set__
    self.set_notify(instance, value)
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\pimpmyclass\props.py", line 474, in set_notify
    self.store(instance, value)
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\pimpmyclass\props.py", line 540, in store
    getattr(instance, self.name + '_changed').emit(value, old_value)
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\PySignal.py", line 129, in emit
    tested_slot(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\nspyre\inserv\inserv.py", line 390, in update_mongo_feat
    self.db[dev_name].update_one({'name': attr},
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\pymongo\collection.py", line 1019, in update_one
    self._update_retryable(
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\pymongo\collection.py", line 868, in _update_retryable
    return self.__database.client._retryable_write(
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\pymongo\mongo_client.py", line 1498, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\pymongo\mongo_client.py", line 1384, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\pymongo\mongo_client.py", line 1416, in _retry_internal
    return func(session, sock_info, retryable)
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\pymongo\collection.py", line 860, in _update
    return self._update(
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\pymongo\collection.py", line 829, in _update
    result = sock_info.command(
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\pymongo\pool.py", line 699, in command
    self._raise_connection_failure(error)
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\pymongo\pool.py", line 683, in command
    return command(self, dbname, spec, slave_ok,
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\pymongo\network.py", line 120, in command
    request_id, msg, size, max_doc_size = message._op_msg(
  File "C:\ProgramData\Miniconda3\envs\nspyre\lib\site-packages\pymongo\message.py", line 714, in _op_msg
    return _op_msg_uncompressed(
bson.errors.InvalidDocument: cannot encode object: 0.16161616161616163, of type: <netref class 'rpyc.core.netref.type'>`

Here my code was just:
`for xval in self.progress(Xsweep, position=0):
   self.vsg.frequency = xval`

If instead I do float(xval) it works. If I pass along Xsweep as a Q_ it works (for a different feat with 'units" defined).
The type of xval when it doesn't work is numpy.float64

**Comment by jacobfeder** [comment]
Is xval an array?

**Comment by jacobfeder** [comment]
I believe this is because mongodb can only accept normal float values and not np.float64. I think the proper solution would be to use float(xval).

**Comment by jacobfeder** [comment]
I'll also say that once we have things properly decoupled from mongodb this shouldn't be an issue, but until then I would use float().
